### ISSUE TITLE
Runtime fails on NoClassDefFoundError: org/apache/log4j/Level

### ISSUE THREAD

**Issue by teledyn** [baharsateli/tdb-exporter#3]
This may be a case of the installed libraries no longer matching the libraries last used in this build; advice online recommends adding corresponding slf4j and log4j jar files, but adding/upgrading these into ./lib does not work.

On Ubuntu 17.10, at runtime we get: 

`Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Level
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at com.hp.hpl.jena.tdb.base.file.MetaFile.<clinit>(MetaFile.java:46)
	at com.hp.hpl.jena.tdb.base.file.Location.<init>(Location.java:105)
	at com.hp.hpl.jena.tdb.base.file.Location.create(Location.java:66)
	at com.hp.hpl.jena.tdb.TDBFactory.createDataset(TDBFactory.java:48)
	at com.baharsateli.lod.convertors.TDBExporter.main(TDBExporter.java:84)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Level
`

**Comment by baharsateli** [comment]
Yeah, looks like there is a new dependency that uses Apache log4j I had excluded from resolution. I updated the Ivy script. Try again and let me know if the issue persists.
